ALTER TABLE items ADD COLUMN IF NOT EXISTS shipping_region TEXT DEFAULT '';
ALTER TABLE items ADD COLUMN IF NOT EXISTS shipping_prefecture TEXT DEFAULT '';
ALTER TABLE items ADD COLUMN IF NOT EXISTS buyer_id TEXT DEFAULT '';
